export const toolPageContent = {
  qrGenerator: {
    path: "/qr-generator",
    title: "QR Generator",
    description: "Generate downloadable PNG, JPG, and SVG QR codes for campaign links, event pages, registration forms, and podcast URLs.",
    socialDescription: "Generate downloadable QR codes for campaign links, event pages, registration forms, and podcast URLs.",
    socialImageAlt: "Trulab Production QR generator utility",
    kicker: "Trulab utility",
    heading: "Generate QR Codes for Production Links",
    introduction: "Create QR codes for proposals, registration pages, show notes, campaign URLs, and client-facing materials. Preview first, then download in the format you need.",
  },
  backgroundRemover: {
    path: "/background-remover",
    title: "Background Remover",
    description: "Remove image backgrounds and export production-ready PNG, WEBP, or JPEG assets with Trulab Production's browser-based tool.",
    socialDescription: "Remove image backgrounds and export production-ready PNG, WEBP, or JPEG assets with Trulab Production's browser-based tool.",
    socialImageAlt: "Trulab Production background remover utility",
    kicker: "Trulab utility",
    heading: "Remove Backgrounds for Production Assets",
    introduction: "Prepare clean thumbnails, speaker profile images, product visuals, and campaign assets directly in the browser. Upload an image, remove the background, adjust export settings, and download.",
  },
} as const;

export const toolInterfaceContent = {
  qrGenerator: {
    title: "QR Generator",
    description: "Convert campaign links, event pages, registration forms, and podcast URLs into downloadable QR codes.",
    emptyError: "Enter a link first.",
    generateError: "Failed to generate QR code.",
    downloadError: "Failed to download QR code.",
    noLoginLabel: "No login required",
    linkLabel: "Link",
    formatLabel: "Format",
    resolutionLabel: "Resolution",
    transparentBackgroundLabel: "Transparent background",
    generatingLabel: "Generating...",
    generateLabel: "Generate QR",
    downloadLabel: "Download",
    previewAriaLabel: "Generated QR preview",
    previewEmptyLabel: "QR preview appears here",
    correctionHelper: "High correction level is enabled for cleaner scanning on printed materials.",
    formats: { png: "PNG", jpg: "JPG", svg: "SVG" },
  },
  backgroundRemover: {
    title: "Background Remover",
    description: "Remove image backgrounds in-browser, then export with transparent, solid color, shadow, and size settings.",
    uploadLabel: "Upload image",
    uploadHelper: "PNG, JPG, or WEBP up to 15MB. Drag and drop supported.",
    chooseFileLabel: "Choose File",
    removeLabel: "Remove Background",
    regenerateLabel: "Generate Again",
    downloadLabel: "Download",
    processingLabel: "Processing...",
    originalLabel: "Original",
    resultLabel: "Result",
    exportSettingsLabel: "Export Settings",
    processingImageLabel: "Processing image...",
    removedImageAlt: "Removed background",
    presets: {
      original: "Original",
      instagram: "Instagram",
      profile: "Profile",
      banner: "Banner",
      square4k: "4K Square",
    },
    fields: {
      size: "Size",
      format: "Format",
      background: "Background",
      shadow: "Shadow",
      quality: "Quality",
      width: "Width",
      height: "Height",
      keepAspectRatio: "Keep aspect ratio",
      backgroundColor: "Background color",
      contrast: "Contrast",
      brightness: "Brightness",
      saturation: "Saturation",
    },
    options: {
      original: "Original",
      small: "Small 512px",
      medium: "Medium 1024px",
      large: "Large 2048px",
      custom: "Custom",
      png: "PNG",
      webp: "WEBP",
      jpeg: "JPEG",
      transparent: "Transparent",
      solidColor: "Solid color",
      none: "None",
      soft: "Soft",
      studio: "Studio",
      floating: "Floating",
    },
    progress: {
      loadingAiModel: "Loading AI model...",
      loadingModel: "Loading model",
      removingBackground: "Removing background...",
    },
    errors: {
      invalidImage: "Please upload a valid image file.",
      imageTooLarge: "Image is too large. Maximum file size is 15MB.",
      uploadFirst: "Upload an image first.",
      removeFailed: "Failed to remove background. Please try another image.",
      prepareFailed: "Failed to prepare image.",
      exportFailed: "Failed to export image.",
      downloadFailed: "Failed to download image.",
    },
  },
} as const;

export const statusPageContent = {
  forbidden: {
    metadataTitle: "403 Forbidden",
    metadataDescription: "Access to this Trulab Production page is restricted.",
    code: "403",
    title: "Access is restricted.",
    description: "You do not have permission to view this page.",
  },
  notFound: {
    metadataTitle: "404 Not Found",
    metadataDescription: "The page you are looking for could not be found on Trulab Production.",
    code: "404",
    title: "Page not found.",
    description: "The page may have moved, expired, or been typed incorrectly. Return to the homepage to continue browsing Trulab Production.",
  },
  maintenance: {
    metadataTitle: "Maintenance",
    metadataDescription: "Trulab Production is temporarily offline for maintenance.",
    title: "Site maintenance in progress.",
    description: "Trulab Production is temporarily offline while updates are being completed. Please check again shortly.",
  },
} as const;

export const contactFormContent = {
  fields: {
    name: "Name",
    company: "Company",
    email: "Email",
    phone: "Phone",
    budget: "Budget",
    message: "Message",
  },
  budgetPlaceholder: "Select budget range",
  submitLabel: "Book Consultation",
  turnstileNotice: "Protected by Cloudflare Turnstile.",
  turnstileMissing: "Anti-spam is not configured yet.",
  turnstileRequired: "Please complete the anti-spam check before submitting.",
  submitFallbackError: "Unable to submit your enquiry.",
  unexpectedError: "Something went wrong. Please try again.",
  success: "Thank you. Your enquiry has been saved and WhatsApp is opening now.",
  whatsapp: {
    introduction: "Hi Trulab Production, I'd like to book a podcast production consultation.",
    detailsHeading: "My details:",
    projectLabel: "Project message",
    closing: "Please let me know the next step. Thank you.",
  },
} as const;
